apiVersion: v1
kind: Secret
metadata:
  name: BasicEnvironmentStatistics-mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password: W0Kg49+fyQZ!liVo # change this to a secure password
#---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: BasicEnvironmentStatistics-mysql-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   selector:
#     matchLabels:
#       app: BasicEnvironmentStatistics-mysql
#   storageClassName: nfs-storage
---
# mysql-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: BasicEnvironmentStatistics-mysql
spec:
  ports:
    - port: 3306 # change this to the desired port if needed
  selector:
    app: BasicEnvironmentStatistics-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: BasicEnvironmentStatistics-mysql # change this to the desired name if needed
spec:
  selector:
    matchLabels:
      app: BasicEnvironmentStatistics-mysql # change this to the desired label if needed
  template:
    metadata:
      labels:
        app: BasicEnvironmentStatistics-mysql # change this to the desired label if needed
    spec:
      containers:
        - image: mysql:5.6 # change this to the desired image if needed
          name: BasicEnvironmentStatistics-mysql # change this to the desired name if needed
          env:
            # Use secret in real usage, see https://kubernetes.io/docs/concepts/configuration/secret/\
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: BasicEnvironmentStatistics-mysql-secret # reference the secret created above, change this to the desired name if needed 
                  key: password # reference the key in the secret, change this to the desired key if needed 
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-data
          ports:
            - containerPort: 3306 # change this to the desired port if needed 
              name: mysql # change this to the desired name if needed 
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: BasicEnvironmentStatistics-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: BasicEnvironmentStatistics
spec:
  ports:
    - port: 80 # change this to the desired port if needed
  selector:
    app: BasicEnvironmentStatistics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: BasicEnvironmentStatistics # change this to the desired name if needed
spec:
  selector:
    matchLabels:
      app: BasicEnvironmentStatistics # change this to the desired label if needed
  template:
    metadata:
      labels:
        app: BasicEnvironmentStatistics # change this to the desired label if needed
    spec:
      containers:
        - image: 192.168.1.199:5000/rescue-system-2024/basicenvironmentstatistics:latest # change this to the desired image if needed
          name: BasicEnvironmentStatistics # change this to the desired name if needed
          env:
            - name: MYSQL_UID
              value: root
            - name: MYSQL_HOST
              value: BasicEnvironmentStatistics-mysql
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: BasicEnvironmentStatistics-mysql-secret # reference the secret created above, change this to the desired name if needed 
                  key: password # reference the key in the secret, change this to the desired key if needed 
          ports:
            - containerPort: 80 # change this to the desired port if needed 
              name: http # change this to the desired name if needed 