spring:
  profiles:
    active: "k8s"
---
server:
  port: 8080

spring:
  application:
    name: BasicEnvironmentStatistics
  config:
    activate:
      on-profile: "k8s"
  datasource:
    url: jdbc:mysql://${MYSQLHOST:127.0.0.1}:3306/statistics?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY_IP}:${REGISTRY_PORT}/eureka


---
server:
  port: 8080
spring:
  application:
    name: BasicEnvironmentStatistics
  config:
    activate:
      on-profile: "dev"
  datasource:
    #    url: jdbc:mysql://172.20.89.20:3306/NotificationService?serverTimezone=CTT
    url: jdbc:mysql://localhost:3306/statistics?createDatabaseIfNotExist=true
    #    url: jdbc:mysql://192.168.0.107:3306/NotificationService?serverTimezone=CTT
    username: mcs_bot
    password: qfkZO8W1ih8WOgWK
    #    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://127.0.0.1:8000/eureka

