spring:
  profiles:
    active: "k8s"
---
server:
  port: 8080

spring:
  application:
    name: BasicEnvironmentStatistics
  config:
    activate:
      on-profile: "k8s"
  datasource:
    url: jdbc:mysql://${MYSQLHOST:127.0.0.1}:3306/statistics?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql


